Parameters:
  SourceBucketName:
    Description: Name the source Bucket
    Type: String
  DataBucketName:
    Description: Name the data Bucket
    Type: String

Resources:
  DbtGlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DbtGlueExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: DbtGlueCustomPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ReadAndWriteDatabases
                Effect: Allow
                Action: ...
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*

              - Sid: ReadAndWriteBuckets
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucketName}
                  - !Sub arn:aws:s3:::${SourceBucketName}/*
                  - !Sub arn:aws:s3:::${DataBucketName}
                  - !Sub arn:aws:s3:::${DataBucketName}/*

              - Sid: AllowPassRoleForGlue
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt DbtGlueExecutionRole.Arn
