Parameters:
  SourceBucketName:
    Description: Name the source Bucket
    Type: String
  DataBucketName:
    Description: Name the data Bucket
    Type: String

Resources:
  DbtGlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DbtGlueExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: DbtGlueCustomPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ReadAndWriteDatabases
                Effect: Allow
                Action:
                  - glue:SearchTables
                  - glue:BatchCreatePartition
                  - glue:CreatePartitionIndex
                  - glue:DeleteDatabase
                  - glue:GetTableVersions
                  - glue:GetPartitions
                  - glue:DeleteTableVersion
                  - glue:UpdateTable
                  - glue:DeleteTable
                  - glue:DeletePartitionIndex
                  - glue:GetTableVersion
                  - glue:UpdateColumnStatisticsForTable
                  - glue:CreatePartition
                  - glue:UpdateDatabase
                  - glue:CreateTable
                  - glue:GetTables
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:GetPartition
                  - glue:UpdateColumnStatisticsForPartition
                  - glue:CreateDatabase
                  - glue:BatchDeleteTableVersion
                  - glue:BatchDeleteTable
                  - glue:DeletePartition
                  - glue:GetUserDefinedFunctions
                  - lakeformation:ListResources
                  - lakeformation:BatchGrantPermissions
                  - lakeformation:ListPermissions
                  - lakeformation:GetDataAccess
                  - lakeformation:GrantPermissions
                  - lakeformation:RevokePermissions
                  - lakeformation:BatchRevokePermissions
                  - lakeformation:AddLFTagsToResource
                  - lakeformation:RemoveLFTagsFromResource
                  - lakeformation:GetResourceLFTags
                  - lakeformation:ListLFTags
                  - lakeformation:GetLFTag
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*

              - Sid: ReadAndWriteBuckets
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucketName}
                  - !Sub arn:aws:s3:::${SourceBucketName}/*
                  - !Sub arn:aws:s3:::${DataBucketName}
                  - !Sub arn:aws:s3:::${DataBucketName}/*

              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"
