Resources:
  DbtGlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DbtGlueExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DbtGlueCustomPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ReadAndWriteDatabases
                Effect: Allow
                Action:
                  - glue:SearchTables
                  - glue:BatchCreatePartition
                  - glue:CreatePartitionIndex
                  - glue:DeleteDatabase
                  - glue:GetTableVersions
                  - glue:GetPartitions
                  - glue:DeleteTableVersion
                  - glue:UpdateTable
                  - glue:DeleteTable
                  - glue:DeletePartitionIndex
                  - glue:GetTableVersion
                  - glue:UpdateColumnStatisticsForTable
                  - glue:CreatePartition
                  - glue:UpdateDatabase
                  - glue:CreateTable
                  - glue:GetTables
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:GetPartition
                  - glue:UpdateColumnStatisticsForPartition
                  - glue:CreateDatabase
                  - glue:BatchDeleteTableVersion
                  - glue:BatchDeleteTable
                  - glue:DeletePartition
                  - glue:GetUserDefinedFunctions
                  - lakeformation:ListResources
                  - lakeformation:BatchGrantPermissions
                  - lakeformation:ListPermissions
                  - lakeformation:GetDataAccess
                  - lakeformation:GrantPermissions
                  - lakeformation:RevokePermissions
                  - lakeformation:BatchRevokePermissions
                  - lakeformation:AddLFTagsToResource
                  - lakeformation:RemoveLFTagsFromResource
                  - lakeformation:GetResourceLFTags
                  - lakeformation:ListLFTags
                  - lakeformation:GetLFTag
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/sales_db/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/sales_db

              - Sid: ReadOnlyDatabases
                Effect: Allow
                Action:
                  - glue:SearchTables
                  - glue:GetTableVersions
                  - glue:GetPartitions
                  - glue:GetTableVersion
                  - glue:GetTables
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:GetPartition
                  - lakeformation:ListResources
                  - lakeformation:ListPermissions
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/bronze/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/bronze
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/default
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/global_temp

              - Sid: StorageAllBuckets
                Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::my-output-bucket
                  - arn:aws:s3:::my-source-bucket

              - Sid: ReadAndWritebuckets
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::my-output-bucket/*

              - Sid: ReadOnlyBuckets
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::my-source-bucket/*
