Description: IAM Role for GitHub Actions to assume via OIDC
Parameters:
  AccountId:
    Description: Account ID
    Type: String
  GitHubRepo:
    Description: GitHub repo in the format org/repo
    Type: String
  # Region:
  #   Description: Region
  #   Type: String
  SourceBucketName:
    Description: Name the source Bucket
    Type: String
  DataBucketName:
    Description: Name the data Bucket
    Type: String

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubRepo}:*
      Policies:
        - PolicyName: GitHubActionsGlueAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:CreateSession
                  - glue:GetSession
                  - glue:DeleteSession
                  - glue:BatchGetSession
                  - glue:RunStatement
                  - glue:GetStatement
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:session/*
              - Effect: Allow
                Action:
                  - glue:SearchTables
                  - glue:BatchCreatePartition
                  - glue:CreatePartitionIndex
                  - glue:DeleteDatabase
                  - glue:GetTableVersions
                  - glue:GetPartitions
                  - glue:DeleteTableVersion
                  - glue:UpdateTable
                  - glue:DeleteTable
                  - glue:DeletePartitionIndex
                  - glue:GetTableVersion
                  - glue:UpdateColumnStatisticsForTable
                  - glue:CreatePartition
                  - glue:UpdateDatabase
                  - glue:CreateTable
                  - glue:GetTables
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:GetPartition
                  - glue:UpdateColumnStatisticsForPartition
                  - glue:CreateDatabase
                  - glue:BatchDeleteTableVersion
                  - glue:BatchDeleteTable
                  - glue:DeletePartition
                  - glue:GetUserDefinedFunctions
                  - lakeformation:ListResources
                  - lakeformation:BatchGrantPermissions
                  - lakeformation:ListPermissions
                  - lakeformation:GetDataAccess
                  - lakeformation:GrantPermissions
                  - lakeformation:RevokePermissions
                  - lakeformation:BatchRevokePermissions
                  - lakeformation:AddLFTagsToResource
                  - lakeformation:RemoveLFTagsFromResource
                  - lakeformation:GetResourceLFTags
                  - lakeformation:ListLFTags
                  - lakeformation:GetLFTag
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !Sub arn:aws:iam::${AccountId}:role/DbtGlueExecutionRole
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucketName}
                  - !Sub arn:aws:s3:::${DataBucketName}

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucketName}/*
                  - !Sub arn:aws:s3:::${DataBucketName}/*
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRuns
                  - glue:GetJob
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/*
              - Effect: Allow
                Action:
                  - glue:StartCrawler
                  - glue:GetCrawler
                  - glue:GetCrawlerMetrics
                  - glue:StopCrawler
                  - glue:UpdateCrawler
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:crawler/*
