Parameters:
  AccountId:
    Description: Account ID
    Type: String

GitHubActionsRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: GitHubActionsRole
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Federated: !Sub arn:aws:iam::${AccountId}:oidc-provider/token.actions.githubusercontent.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringLike:
              token.actions.githubusercontent.com:sub: repo:<GitHubOrg>/<RepoName>:*
    Policies:
      - PolicyName: GitHubActionsGlueAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - glue:StartJobRun
                - glue:StartSession
                - glue:GetJobRun
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: arn:aws:iam::<ACCOUNT_ID>:role/DbtGlueExecutionRole
