Parameters:
  SourceBucketName:
    Description: Name the source Bucket
    Type: String
  DataBucketName:
    Description: Name the data Bucket
    Type: String
  ScriptName:
    Description: Name the script
    Type: String
  JobName:
    Description: Name the Glue Job
    Type: String

Resources:
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Tags:
        - Key: Name
          Value: GlueServiceRole
      Policies:
        - PolicyName: GlueCustomAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${SourceBucketName}"
                  - !Sub "arn:aws:s3:::${SourceBucketName}/*"
                  - !Sub "arn:aws:s3:::${DataBucketName}"
                  - !Sub "arn:aws:s3:::${DataBucketName}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:DescribeLogGroups
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: "*"
              - Effect: Allow
                Action:
                  - glue:GetConnection
                  - glue:GetConnections
                Resource: "*"
              - Effect: Allow
                Action:
                  - codewhisperer:GenerateRecommendations
                  - codewhisperer:ListRecommendations
                  - codewhisperer:GetRecommendation
                Resource: "*"

  SnowflakeGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Name: snowflake-connection
        ConnectionType: SNOWFLAKE
        Description: Glue connection to Snowflake using Secrets Manager
        ConnectionProperties:
          CONNECTION_NAME: snowflake-connection
          SECRET_ID: snowflake
          JDBC_CONNECTION_URL: "jdbc:snowflake://DHAHNFX-AM43103.snowflakecomputing.com:443"
        # Optional: Uncomment the following if using VPC interface endpoints
        # PhysicalConnectionRequirements:
        #   SubnetId: !Ref GlueSubnetId
        #   SecurityGroupIdList:
        #     - !Ref GlueSecurityGroup

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref JobName
      Role: !GetAtt GlueServiceRole.Arn
      Description: "Glue Spark job to ingest data from Snowflake"
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 5
      Timeout: 3
      ExecutionClass: FLEX
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${SourceBucketName}/scripts/${ScriptName}"
        PythonVersion: "3"
      DefaultArguments:
        "--TempDir": !Sub "s3://${DataBucketName}/tmp/"
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--conf": "spark.sql.sources.partitionOverwriteMode=dynamic"
        "--SF_SECRET_NAME": "snowflake"
        "--TARGET_S3_BUCKET": !Ref SourceBucketName
      Connections:
        Connections:
          - snowflake-connection
      Tags:
        Environment: dev
