Parameters:
  SourceBucketName:
    Description: Name the source Bucket
    Type: String
  DataBucketName:
    Description: Name the data Bucket
    Type: String

Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: sales-aggregation-job
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${SourceBucketName}/scripts/sales_etl.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://${DataBucketName}/tmp/"
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
      Connections:
        Connections:
          - redshift-demo-connection
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      WorkerType: G.1X
      NumberOfWorkers: 5
      Tags:
        Environment: dev
