Parameters:
  SourceBucketName:
    Description: Name the source Bucket
    Type: String
  DataBucketName:
    Description: Name the data Bucket
    Type: String
  ScriptName:
    Description: Name the script
    Type: String
  JobName:
    Description: Name the Glue Job
    Type: String

Resources:
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Tags:
        - Key: Name
          Value: GlueServiceRole
      Policies:
        - PolicyName: GlueCustomAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # S3 Access (read/write for both buckets)
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${SourceBucketName}"
                  - !Sub "arn:aws:s3:::${SourceBucketName}/*"
                  - !Sub "arn:aws:s3:::${DataBucketName}"
                  - !Sub "arn:aws:s3:::${DataBucketName}/*"

              # CloudWatch Logs access
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # Secrets Manager access for Redshift credentials resolution
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: "*"

              # Allow Glue to use connections (e.g., Redshift)
              - Effect: Allow
                Action:
                  - glue:GetConnection
                  - glue:GetConnections
                Resource: "*"

              # to allow CodeWhisperer actions
              - Effect": Allow
                Action:
                  - codewhisperer:GenerateRecommendations
                  - codewhisperer:ListRecommendations
                  - codewhisperer:GetRecommendation
                Resource: "*"

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${JobName}"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${SourceBucketName}/scripts/${ScriptName}"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://${DataBucketName}/tmp/"
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
      Connections:
        Connections:
          - redshift-demo-connection
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      WorkerType: G.1X
      NumberOfWorkers: 5
      Tags:
        Environment: dev
      VpcConfig:
        SubnetId: !ImportValue vpc-stack-PrivateSubnet1
        SecurityGroupIds:
          - !ImportValue GlueJobSG # Define this SG to allow Redshift port (5439)

