on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "ap-southeast-2"
      SourceBucketName:
        description: "S3 Source Bucket Name"
        default: "source-bucket-chien"
        required: true
      DataBucketName:
        description: "S3 Data Bucket Name"
        default: "data-bucket-chien"

jobs:
  deploy-dbt-glue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds-pipeline
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Get AWS account ID
        id: get-account
        run: echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> "$GITHUB_ENV"

      - name: Deploy Github action role

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ github.event.inputs.region }}

      - name: Install AWS CLI and dbt-glue
        run: |
          pip install awscli dbt-core dbt-glue

      - name: Create dbt profiles.yml
        run: ./pipeline/create_profiles.sh
        env:
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
          REGION: ${{ github.event.inputs.region }}
          SOURCE_BUCKET: ${{ github.event.inputs.SourceBucketName }}
          DATA_BUCKET: ${{ github.event.inputs.DataBucketName }}

      - name: Run dbt on Glue Interactive Sessions
        env:
          AWS_REGION: ap-southeast-2
        run: |
          dbt run --profiles-dir ~/.dbt/ dbt_glue --project-dir dbt_glue/
