version: 2

models:
  - name: order_products
    description: "Joined prior and train order products with eval set label"
    columns:
      - name: order_id
        description: "The ID of the order"
        tests:
          - not_null

      - name: product_id
        description: "The ID of the product"
        tests:
          - not_null

      - name: add_to_cart_order
        description: "The order in which the item was added to the cart"

      - name: reordered
        description: "Whether the product was reordered"

      - name: eval_set
        description: "Data split type: 'prior' or 'train'"
